[package]
name        =  "jsw"
version     =  "0.0.1"
description =  "JavaScript Workout /Rust extension/"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
repository  =  "https://github.com/ponyatov/Evento"
edition     =  "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
const_format = "0.2"
